### PR TITLE
change online from red to green

### PR DESCRIPTION
**Pull request by YaguraStation**
2020-04-07-20-14-00_437x744

### CODE REVIEW

**Comment by tyrasd** [comment]
~~Thanks. Just one issue, while we're at it: can you maybe also convert the text to a path? Because if one doesn't have the _Roboto_ font, the result doesn't look exactly the same on every system. E.g. this is how it looks like for me on Ubuntu:~~

image

~~on Windows it's not that bad, but it's also not 100% as it should be.~~

Oh, Christine was a bit too fast :sweat_smile: – I've opened #31 for it.

**Comment by YaguraStation** [comment]
@tyrasd Does it also look like this in your browser? I left the fonts editable for anyone on the team to edit it in a SVG editor like Inkscape. (Debian here)

**Comment by tyrasd** [comment]
yes, see https://github.com/openstreetmap/stateofthemap-2020/issues/31#issue-596088963

maybe you can add both an editable version "for the team" and a rendered one for "production" on the website?

**Comment by YaguraStation** [comment]
Yeah, I think it shouldn't be a problem for someone to write it out again. See #32

**Pull request merged**
